### PR TITLE
Add PATH to SwiftLint script (+Bundle update)

### PR DESCRIPTION
**Pull request by diktomat**
I'm thinking of contributing a little in future, so first task was to get it build. As bundler told me `google-api-client (0.38.0)` was removed, I had to bundle update. All tests succeed, so no harm done there.

Additionally, I added (as recommended in SwiftLint's README) Homebrew's bin dir to PATH in the SwiftLint build phase, so Xcode can find it. As SwiftLint is downloaded via brew by `make dependencies`, this seems to be a sensible default for all here.

### CODE REVIEW

**Review by mltbnz — APPROVED** [review]
Thanks for the update.

You are very welcome to contribute.

since I don't know if the app is ever going to be released I wanted to give a fair word of warning just to manage some expectations.

**Comment by phoet** [comment]
@mltbnz I hope it will get released, i think it's just not ready for that

**Comment by mltbnz** [comment]
@phoet What do you think is missing?

I'd say #4 is mostly implemented but atm it is definitely more of a mvp.

**Comment by mltbnz** [comment]
But we can merge this first I think and maybe pick up the discussion in #4 😄

**Comment by phoet** [comment]
If you think the app is ready, please go for it! There are probably dozens of users happy to beta-test it.

**Comment by mltbnz** [comment]
I honestly need to check again if this could already make a beta since it's been a while but maybe getting some feedback from users could be helpful to find out what's missing.

In this first version I wanted to give the existing skeleton of the app some more functionality and in the end be able to compose the email but for it to be a really nice app things are missing for sure. But I think you did collect most points already in the issues

**Pull request merged**
